[project]
name = "humanai-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.22.0",
    "pypdf2>=3.0.1",
    "requests>=2.32.3",
]
